"""added queue statistics

Revision ID: 4bf724d3d547
Revises: ac392f9cfa89
Create Date: 2021-09-26 18:57:15.298796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf724d3d547'
down_revision = 'ac392f9cfa89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domainname', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_domainname'), 'domain', ['domainname'], unique=True)
    op.create_table('global_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('TotalMessagesInbound', sa.Integer(), nullable=True),
    sa.Column('TotalMessagesOutbound', sa.Integer(), nullable=True),
    sa.Column('MeanTimeInQueueInbound', sa.Integer(), nullable=True),
    sa.Column('MeanTimeInQueueOutbound', sa.Integer(), nullable=True),
    sa.Column('LongestTimeInInbound', sa.Integer(), nullable=True),
    sa.Column('LongestTimeInOutbound', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_queue_datetime'), 'global_queue', ['datetime'], unique=False)
    op.create_table('domain_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('ReceiveQueueCountInbound', sa.Integer(), nullable=True),
    sa.Column('ReceiveQueueCountOutbound', sa.Integer(), nullable=True),
    sa.Column('DeliveryQueueCountInbound', sa.Integer(), nullable=True),
    sa.Column('DeliveryQueueCountOutbound', sa.Integer(), nullable=True),
    sa.Column('LongestTimeInReceiveQueueInbound', sa.Integer(), nullable=True),
    sa.Column('LongestTimeInReceiveQueueOutbound', sa.Integer(), nullable=True),
    sa.Column('LongestTimeInDeliveryQueueInbound', sa.Integer(), nullable=True),
    sa.Column('LongestTimeInDeliveryQueueOutbound', sa.Integer(), nullable=True),
    sa.Column('MeanTimeInReceiveQueueInbound', sa.Integer(), nullable=True),
    sa.Column('MeanTimeInReceiveQueueOutbound', sa.Integer(), nullable=True),
    sa.Column('MeanTimeInDeliveryQueueInbound', sa.Integer(), nullable=True),
    sa.Column('MeanTimeInDeliveryQueueOutbound', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_queue_datetime'), 'domain_queue', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_queue_datetime'), table_name='domain_queue')
    op.drop_table('domain_queue')
    op.drop_index(op.f('ix_global_queue_datetime'), table_name='global_queue')
    op.drop_table('global_queue')
    op.drop_index(op.f('ix_domain_domainname'), table_name='domain')
    op.drop_table('domain')
    # ### end Alembic commands ###
